spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: r1
            uri: http://localhost:8080
            predicates:
              - Path = /service-1/**
          - id: r2
            uri: http://localhost:8081
            predicates:
              - Path = /service-2/** 